// Simple Yul code emitter.
//
// This is intentionally minimal. The full SAIL compilation pipeline performs
// type checking, monomorphisation, match compilation, and a Hull lowering step
// before reaching Yul. For this simple compiler we emit a syntactically
// correct Yul object that:
//
//   * Wraps everything in `object "SAIL" { code { ... } object "runtime" { ... } }`
//   * Emits one Yul function per concrete (no `forall`) SAIL function whose
//     parameter and return types are all `word`/`bool`/`()`/unit-wrappers.
//   * Inlines verbatim Yul from `assembly { ... }` blocks.
//   * Folds simple `let` declarations of `word`-typed locals; everything else
//     is dropped, so non-assembly bodies generally become `<retname> := 0`.
//
// The intent is that `sailc std/std.solc -o out.yul` produces a Yul file that
// `solc --strict-assembly` (or another Yul consumer) will accept syntactically.

use crate::ast::*;
use std::collections::{HashMap, HashSet};
use std::fmt::Write;

pub struct Emitter {
    out: String,
    indent: usize,
    /// Mangled function names already emitted, to avoid duplicates from
    /// instance methods that share a base name.
    emitted: HashSet<String>,
    /// Within the current function body: how many times each name has been
    /// `let`-bound. Used to make shadowed declarations unique for Yul (which
    /// forbids re-declaring a variable in the same scope).
    locals: HashMap<String, usize>,
    /// Mapping from the SAIL local name in-scope right now → its Yul name.
    /// On `let x` we bump the counter and update this map.
    rename: HashMap<String, String>,
}

impl Emitter {
    pub fn new() -> Self {
        Emitter {
            out: String::new(),
            indent: 0,
            emitted: HashSet::new(),
            locals: HashMap::new(),
            rename: HashMap::new(),
        }
    }

    fn fresh_local(&mut self, base: &str) -> String {
        let count = self.locals.entry(base.to_string()).or_insert(0);
        let name = if *count == 0 { base.to_string() } else { format!("{}_{}", base, *count) };
        *count += 1;
        self.rename.insert(base.to_string(), name.clone());
        name
    }

    fn lookup_local(&self, base: &str) -> String {
        self.rename.get(base).cloned().unwrap_or_else(|| base.to_string())
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent { self.out.push(' '); self.out.push(' '); }
        self.out.push_str(s);
        self.out.push('\n');
    }

    pub fn emit_unit(&mut self, unit: &CompUnit, module_name: &str) -> String {
        self.line(&format!("// Generated by sailc for module {}", module_name));
        self.line(&format!("object \"{}\" {{", sanitize(module_name)));
        self.indent += 1;
        self.line("code {");
        self.indent += 1;
        self.line("// Constructor: copy runtime sub-object to memory and return it.");
        self.line(&format!("datacopy(0, dataoffset(\"{}_runtime\"), datasize(\"{}_runtime\"))",
            sanitize(module_name), sanitize(module_name)));
        self.line(&format!("return(0, datasize(\"{}_runtime\"))", sanitize(module_name)));
        self.indent -= 1;
        self.line("}");
        self.line(&format!("object \"{}_runtime\" {{", sanitize(module_name)));
        self.indent += 1;
        self.line("code {");
        self.indent += 1;
        self.line("// Default entry point.");
        self.line("revert(0, 0)");

        // Collect contributing functions: top-level free functions plus
        // instance methods. Class signatures (bodyless) and polymorphic
        // definitions are skipped.
        for d in &unit.decls {
            match d {
                TopDecl::Func(f) => self.emit_function(f, None),
                TopDecl::Instance(inst) => {
                    let inst_tag = type_tag(&inst.head_ty);
                    let class_tag = inst.class_name.join("_");
                    for m in &inst.methods {
                        let prefix = format!("{}__{}__", class_tag, inst_tag);
                        self.emit_function(m, Some(&prefix));
                    }
                }
                _ => {}
            }
        }

        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        std::mem::take(&mut self.out)
    }

    /// Emit a single SAIL function as a Yul function. Skips polymorphic
    /// definitions (anything with a `forall` prefix on the signature) since
    /// monomorphisation is not implemented here.
    fn emit_function(&mut self, f: &Function, name_prefix: Option<&str>) {
        if f.sig.prefix.is_some() {
            // Polymorphic / constrained: skipped by the simple back end.
            return;
        }
        if f.body.is_none() && f.short.is_none() {
            // Bare signature (class method declaration).
            return;
        }
        // Determine which parameters are word-shaped. Anything that is not
        // word/bool/unit/typedef-wrapper is treated opaquely as a word slot.
        let params: Vec<&str> = f.sig.params.iter().map(|p| p.name.as_str()).collect();
        let has_return = !matches!(&f.sig.ret, Some(Type::Tuple(v)) if v.is_empty());

        let mangled = match name_prefix {
            Some(p) => format!("{}{}", p, f.sig.name),
            None => f.sig.name.clone(),
        };
        if !self.emitted.insert(mangled.clone()) {
            return;
        }

        // Reset per-function rename state. Parameters seed the rename map so
        // their names are stable (they are guaranteed unique by SAIL).
        self.locals.clear();
        self.rename.clear();
        for p in &params {
            self.locals.insert((*p).to_string(), 1);
            self.rename.insert((*p).to_string(), (*p).to_string());
        }

        let mut header = format!("function {}(", yul_ident(&mangled));
        for (i, n) in params.iter().enumerate() {
            if i > 0 { header.push_str(", "); }
            header.push_str(&sanitize_local(n));
        }
        header.push(')');
        if has_return {
            header.push_str(" -> _ret");
        }
        header.push_str(" {");
        self.line(&header);
        self.indent += 1;

        if let Some(body) = &f.body {
            self.emit_body(body, has_return);
        } else if let Some(_e) = &f.short {
            if has_return {
                self.line("_ret := 0 // short-form body: replaced with 0");
            }
        }

        if has_return {
            // Defensive: ensure _ret is assigned even if no return found.
            // Yul allows declared but unassigned named-return vars (= 0).
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_body(&mut self, body: &Body, has_return: bool) {
        for s in &body.stmts {
            self.emit_stmt(s, has_return);
        }
    }

    fn emit_stmt(&mut self, s: &Stmt, has_return: bool) {
        match s {
            Stmt::Let(name, _ty, init) => {
                let rhs = init.as_ref().and_then(|e| self.try_eval_word_expr(e));
                let yname = self.fresh_local(name);
                match rhs {
                    Some(r) => self.line(&format!("let {} := {}", yname, r)),
                    None => self.line(&format!("let {} := 0", yname)),
                }
            }
            Stmt::Asm(blk) => {
                for ys in &blk.stmts {
                    self.emit_yul_stmt(ys);
                }
            }
            Stmt::Return(e) => {
                if has_return {
                    let rhs = e.as_ref()
                        .and_then(|e| self.try_eval_word_expr(e))
                        .unwrap_or_else(|| "0".to_string());
                    self.line(&format!("_ret := {}", rhs));
                }
                self.line("leave");
            }
            Stmt::Match(_, _) | Stmt::If(_, _, _) | Stmt::Expr(_)
                | Stmt::Assign(_, _) | Stmt::AddAssign(_, _) | Stmt::SubAssign(_, _) => {
                // Without monomorphised dispatch we can't faithfully lower
                // these; the only effect we preserve is from assembly blocks
                // already handled above.
            }
        }
    }

    fn emit_yul_stmt(&mut self, s: &YulStmt) {
        match s {
            YulStmt::Let(names, init) => {
                // Yul `let` introduces fresh variables. If the name already
                // exists in this function we rename to avoid Yul's no-shadow
                // rule. We rewrite the rhs first (using the *old* binding).
                let rhs = init.as_ref().map(|e| self.yul_expr_str(e));
                let renamed: Vec<String> = names.iter().map(|n| self.fresh_local(n)).collect();
                let joined = renamed.join(", ");
                match rhs {
                    Some(r) => self.line(&format!("let {} := {}", joined, r)),
                    None => self.line(&format!("let {}", joined)),
                }
            }
            YulStmt::Assign(lhs, rhs) => {
                let r = self.yul_expr_str(rhs);
                let n = lhs.iter().map(|x| self.lookup_local(&x.0)).collect::<Vec<_>>().join(", ");
                self.line(&format!("{} := {}", n, r));
            }
            YulStmt::ExprStmt(e) => { let s = self.yul_expr_str(e); self.line(&s); }
            YulStmt::If(c, body) => {
                let cs = self.yul_expr_str(c);
                self.line(&format!("if {} {{", cs));
                self.indent += 1;
                for s in body { self.emit_yul_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            YulStmt::Switch(scr, cases, default) => {
                let ss = self.yul_expr_str(scr);
                self.line(&format!("switch {}", ss));
                for c in cases {
                    let v = match &c.value {
                        YulLit::Int(s) => s.clone(),
                        YulLit::Str(s) => format!("\"{}\"", s),
                    };
                    self.line(&format!("case {} {{", v));
                    self.indent += 1;
                    for s in &c.body { self.emit_yul_stmt(s); }
                    self.indent -= 1;
                    self.line("}");
                }
                if let Some(d) = default {
                    self.line("default {");
                    self.indent += 1;
                    for s in d { self.emit_yul_stmt(s); }
                    self.indent -= 1;
                    self.line("}");
                }
            }
            YulStmt::For(init, cond, post, body) => {
                self.line("for {");
                self.indent += 1;
                for s in init { self.emit_yul_stmt(s); }
                self.indent -= 1;
                let cs = self.yul_expr_str(cond);
                self.line(&format!("}} {} {{", cs));
                self.indent += 1;
                for s in post { self.emit_yul_stmt(s); }
                self.indent -= 1;
                self.line("} {");
                self.indent += 1;
                for s in body { self.emit_yul_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            YulStmt::Break => self.line("break"),
            YulStmt::Continue => self.line("continue"),
            YulStmt::Leave => self.line("leave"),
            YulStmt::FunctionDef(name, params, rets, body) => {
                // Nested Yul function: introduce its own local scope so the
                // surrounding rename map is not perturbed by names declared
                // inside.
                let saved_locals = std::mem::take(&mut self.locals);
                let saved_rename = std::mem::take(&mut self.rename);
                for p in params { self.locals.insert(p.clone(), 1); self.rename.insert(p.clone(), p.clone()); }
                for r in rets { self.locals.insert(r.clone(), 1); self.rename.insert(r.clone(), r.clone()); }

                let mut h = format!("function {}({})", sanitize_local(name),
                    params.iter().map(|p| sanitize_local(p)).collect::<Vec<_>>().join(", "));
                if !rets.is_empty() {
                    h.push_str(" -> ");
                    h.push_str(&rets.iter().map(|r| sanitize_local(r)).collect::<Vec<_>>().join(", "));
                }
                h.push_str(" {");
                self.line(&h);
                self.indent += 1;
                for s in body { self.emit_yul_stmt(s); }
                self.indent -= 1;
                self.line("}");

                self.locals = saved_locals;
                self.rename = saved_rename;
            }
            YulStmt::Block(stmts) => {
                self.line("{");
                self.indent += 1;
                for s in stmts { self.emit_yul_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
        }
    }
}

// ----- helpers ---------------------------------------------------------------

fn sanitize_local(s: &str) -> String { s.to_string() }

impl Emitter {
    fn yul_expr_str(&self, e: &YulExpr) -> String {
        match e {
            YulExpr::Lit(YulLit::Int(s)) => s.clone(),
            YulExpr::Lit(YulLit::Str(s)) => format!("\"{}\"", s),
            YulExpr::Var(n) => self.lookup_local(n),
            YulExpr::Call(f, args) => {
                // Function call: function names are Yul builtins or
                // user-defined Yul functions, never local variables. Don't
                // run them through the rename map.
                let inner = args.iter().map(|a| self.yul_expr_str(a)).collect::<Vec<_>>().join(", ");
                format!("{}({})", sanitize_local(f), inner)
            }
        }
    }

    /// Best-effort: lower a SAIL expression to a single Yul expression string.
    /// Only handles trivially closed forms (literals, in-scope variables).
    fn try_eval_word_expr(&self, e: &Expr) -> Option<String> {
        match e {
            Expr::Int(s) => Some(s.clone()),
            Expr::Bool(true) => Some("1".into()),
            Expr::Bool(false) => Some("0".into()),
            Expr::Var(path) if path.len() == 1 => Some(self.lookup_local(&path[0])),
            _ => None,
        }
    }
}

fn sanitize(s: &str) -> String {
    s.chars().map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }).collect()
}

/// Yul identifier rules are roughly the same as SAIL's; reserved Yul names
/// (`address`, `byte`, `return`, ...) used as SAIL function names are
/// rewritten so we don't collide with Yul builtins.
fn yul_ident(name: &str) -> String {
    const RESERVED: &[&str] = &[
        "return", "revert", "address", "byte", "and", "or", "not", "mod",
        "lt", "gt", "eq", "iszero", "if", "switch", "case", "default",
        "for", "let", "function", "break", "continue", "leave",
        "calldataload", "calldatacopy", "calldatasize",
        "mload", "mstore", "sload", "sstore", "keccak256", "log0", "log1",
        "log2", "log3", "log4", "selfbalance", "balance", "caller", "callvalue",
        "calldataload", "origin", "gasprice", "extcodesize", "extcodecopy",
        "extcodehash", "blockhash", "coinbase", "timestamp", "number",
        "difficulty", "prevrandao", "gaslimit", "chainid", "basefee",
        "blobhash", "blobbasefee", "gas", "selfdestruct",
        "create", "create2", "call", "callcode", "delegatecall", "staticcall",
        "returndatasize", "returndatacopy", "mcopy", "memoryguard",
        "string", "bool", "true", "false", "data", "type",
    ];
    if RESERVED.contains(&name) {
        format!("sail_{}", name)
    } else {
        name.to_string()
    }
}

// Encode a type as a short, monomorphic tag for instance-method mangling.
fn type_tag(t: &Type) -> String {
    let mut s = String::new();
    write_type_tag(t, &mut s);
    sanitize(&s)
}

fn write_type_tag(t: &Type, out: &mut String) {
    match t {
        Type::Named(p, args) => {
            let _ = write!(out, "{}", p.join("_"));
            if !args.is_empty() {
                out.push('_');
                for (i, a) in args.iter().enumerate() {
                    if i > 0 { out.push('_'); }
                    write_type_tag(a, out);
                }
            }
        }
        Type::Tuple(args) => {
            out.push_str("tup");
            for a in args { out.push('_'); write_type_tag(a, out); }
        }
        Type::Fun(args, ret) => {
            out.push_str("fn");
            for a in args { out.push('_'); write_type_tag(a, out); }
            out.push('_');
            write_type_tag(ret, out);
        }
        Type::Proxy(t) => { out.push_str("proxy_"); write_type_tag(t, out); }
        Type::Var(n) => out.push_str(n),
    }
}
